global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "content-cache"
    scheme: https
    tls_config:
      ca_file: ../.cert/cert.pem
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9443"]
